"""
Language Intelligence - Response Generation Context
========================================================
Prompt 426. The bridge between the existing structured planning layer
and the language backend a response is actually generated by:

    LanguageUnderstandingResult
      -> ResponsePlan                         (response_planning.py, Prompt 425)
      -> ResponseGenerationContext            (this module)
      -> LanguageIntelligenceBackend.generate_response()
         (DeterministicFallbackBackend / LocalLanguageModelBackend)

This module implements NO natural-language generation. It only takes
what `ResponsePlanner.plan()` already decided and exposes it as a
small, bounded, read-only object a backend's generation path can read
- nothing here adds a fact, a meaning, a variable or a response action
that the `ResponsePlan` did not already carry.

What it carries (all copied from the `ResponsePlan`, never recomputed)
------------------------------------------------------------------------
    original_message          `ResponsePlan.original_message`, verbatim
    normalized_input          Prompt 610: `ResponsePlan.normalized_input`
                              (itself forwarded verbatim from
                              `LanguageUnderstandingResult.normalized_input`,
                              Prompt 609 - the existing Understanding
                              Engine's own normalization,
                              understanding/normalization.py), carried
                              through unchanged. Never recomputed or
                              re-normalized here; kept separate from
                              `original_message` above, exactly as the
                              plan itself keeps it separate. `None` when
                              the plan carries none (a hand-built plan/
                              dict predating Prompt 609, or omitted on
                              direct construction) - the SAME "additive,
                              forwarded verbatim" posture
                              `correction_application_result_usable`
                              below already uses.
    status                    RESOLVED / AMBIGUOUS / UNRESOLVED, unchanged
    response_action           `ResponsePlan.response_action` - None unless
                              the plan is RESOLVED and an action was
                              explicitly taught/looked up; never guessed
    meaning                   the one resolved bound meaning, or None
    meaning_candidates        undecided candidates, when the plan is
                              AMBIGUOUS via the meaning binder; [] otherwise
    matched_pattern           the matched learned pattern, or None
    variables                 the matched pattern's extracted variables
    active_topic              the plan's active topic, or None
    references                the plan's referenced items
    context                   the plan's conversation context, or None
    language                  `ResponsePlan.detected_language`
    locale                    `ResponsePlan.locale`
    unresolved_requirements   what the plan could not settle
    language_guidance         Prompt 433: the bounded `LearnedLanguageGuidance`
                              (language_guidance.py) built from this SAME
                              `ResponsePlan` (and, when available,
                              `sentence_structure`) - already-learned
                              pattern meaning, expression meanings and
                              recognized sentence structure, reshaped for
                              response generation to read. Never invented
                              here; see language_guidance.py's own module
                              docstring for exactly what it does and does
                              not include.
    response_pattern_selection  Prompt 434: the deterministic
                              `LearnedResponsePatternSelection`
                              (learned_response_pattern_selection.py)
                              made from this SAME `ResponsePlan` and the
                              `language_guidance` just built - which
                              already-taught learned response pattern
                              applies (RESOLVED), which ones apply
                              equally (AMBIGUOUS, all kept) or that none
                              does (NOT_FOUND). Never generated or
                              invented here; see that module's own
                              docstring. Selection runs AFTER guidance
                              and BEFORE the context is built:
                              understanding -> guidance -> selection ->
                              context -> request.
    response_pattern_binding    Prompt 435: the deterministic
                              `LearnedResponsePatternBinding`
                              (learned_response_pattern_binding.py)
                              made from this SAME `ResponsePlan`, the
                              `language_guidance` and the selection just
                              built - the variables the ONE selected
                              response pattern needs, bound to values the
                              pipeline already extracted (RESOLVED), or
                              which of them could not be (UNRESOLVED);
                              an AMBIGUOUS / NOT_FOUND selection is
                              preserved unbound. Never generated or
                              invented here; see that module's own
                              docstring. Binding runs AFTER selection and
                              BEFORE the context is built:
                              understanding -> guidance -> selection ->
                              binding -> context -> request.
    response_pattern_rendering  Prompt 436: the deterministic
                              `LearnedResponsePatternRendering`
                              (learned_response_pattern_rendering.py)
                              made from the binding just built - the ONE
                              selected pattern's template with its bound
                              variables substituted (RESOLVED, with
                              `rendered_text`), or which variables are
                              missing (UNRESOLVED, no text); an
                              AMBIGUOUS / NOT_FOUND binding is preserved
                              unrendered. Deterministic learned-response
                              output, never model output; never
                              generated or invented here. Rendering runs
                              AFTER binding and BEFORE the context is
                              built: understanding -> guidance ->
                              selection -> binding -> rendering ->
                              context -> request.
    correction_lookup_context   Prompt 467: the existing
                              `LanguageUnderstandingResult.
                              correction_lookup_context` (Prompt 466's
                              `CorrectionLookupContext`, when the
                              understanding this context is built from
                              carries one), copied straight through
                              unchanged - `build_generation_context()`
                              does not perform a lookup, does not
                              decide when one should happen, and this
                              field does not influence anything else
                              built here (`response_action`, guidance,
                              selection, binding, rendering are all
                              computed exactly as before, from the SAME
                              `ResponsePlan` alone). `None` whenever the
                              understanding carried no correction lookup
                              context - the common case - so nothing
                              changes for existing callers. Purely
                              informational, exactly like Prompt 466's
                              own field on `LanguageUnderstandingResult`.
    correction_application_candidate  Prompt 471: the existing Prompt
                              470 `CorrectionApplicationCandidate`
                              (correction_application_candidate.py),
                              when a caller explicitly supplies one -
                              copied straight through unchanged, the
                              SAME "carry an already-built object
                              through, never compute it here" posture
                              the `correction_lookup_context` field
                              just above already uses.
                              `build_generation_context()` does not
                              build a candidate, does not decide when
                              one applies, and this field does not
                              influence anything else built here
                              (`response_action`, guidance, selection,
                              binding, rendering, and even
                              `correction_lookup_context` are all
                              computed exactly as before). `None`
                              unless a caller explicitly passes one -
                              so nothing changes for any existing
                              caller. Purely informational - see
                              correction_application_candidate.py's own
                              module docstring for what "valid" means
                              and for the reminder that deciding
                              whether/how to use one is a separate,
                              future, explicitly scoped step.
    correction_application_result  Prompt 483: the existing
                              `CorrectionApplicationResult` (Prompt
                              474/478/479, typically one already
                              produced and verified by Prompt 482's
                              `apply_correction_request_with_validation()`),
                              when a caller explicitly supplies one -
                              copied straight through unchanged, the
                              SAME "carry an already-built object
                              through, never compute, apply, or modify
                              it here" posture `correction_lookup_context`
                              and `correction_application_candidate`
                              (just above) already use.
                              `build_generation_context()` does not
                              apply a correction, does not validate or
                              re-verify the result, does not decide
                              when one applies, and this field does
                              not influence anything else built here
                              or interpret/branch on the result's own
                              `status` in any way - an `APPLIED` result
                              is stored exactly like a `NOT_APPLIED` or
                              `FAILED` one, and none of the three is
                              ever treated as, or converted into,
                              another. `None` unless a caller
                              explicitly passes one - so nothing
                              changes for any existing caller. Purely
                              informational; consuming or interpreting
                              it is a separate, future, explicitly
                              scoped step - see
                              correction_application_result.py's own
                              module docstring for the result shape
                              itself.

    verified_correction_response_input  Prompt 487: the existing
                              `VerifiedCorrectionResponseInput` (Prompt
                              485, verified_correction_response_input.py),
                              when a caller explicitly supplies one -
                              copied straight through unchanged, the
                              SAME "carry an already-built object
                              through, never compute, apply, or modify
                              it here" posture `correction_lookup_context`,
                              `correction_application_candidate` and
                              `correction_application_result` (just
                              above) already use.
                              `build_generation_context()` does not
                              build one, does not perform correction
                              application, matching, or automatic
                              correction, and does not decide when one
                              applies - it does not change the
                              generated response text, and it does not
                              influence anything else built here.
                              `None` unless a caller explicitly passes
                              one - so nothing changes for any existing
                              caller. Purely informational; the local
                              model does not consume this field yet -
                              see verified_correction_response_input.py's
                              own module docstring for the structure
                              itself.

    corrected_response_target  Prompt 494: the prepared corrected
                              response target text (Prompt 493's
                              `prepare_corrected_response_target()`,
                              corrected_response_target.py), when a
                              caller explicitly supplies one, or `None`
                              - carried straight through unchanged, the
                              SAME "carry an already-computed value
                              through, never compute, apply, or modify
                              it here" posture the correction fields
                              just above already use. Unlike those
                              fields, this one is NOT a parameter of
                              `build_generation_context()` below -
                              `with_corrected_response_target()`
                              (corrected_response_target_context.py) is
                              the one place that attaches it, from an
                              existing `ResponseGenerationRequest`, to
                              an already-built `ResponseGenerationContext`.
                              `None` unless explicitly attached - so
                              nothing changes for any existing caller.
                              Purely informational; it does not change
                              the generated response text and does not
                              influence anything else built here.

    correction_application_result_usable  Prompt 575: the existing
                              `ResponsePlan.correction_application_result_usable`
                              (Prompt 574, itself derived from
                              `ResponsePlan.correction_application_result`
                              - Prompt 573 - by the EXISTING Prompt 484
                              `is_correction_application_result_usable()`
                              criteria), forwarded here unchanged -
                              never independently recomputed, re-derived,
                              or re-evaluated by this module. `False`
                              when the plan carries no such field (every
                              existing caller/plan from before Prompt
                              574 - the common case), so nothing changes
                              for any existing caller. Purely
                              informational, exactly like
                              `correction_application_result` above:
                              it plays no part in `guidance`/
                              `selection`/`binding`/`rendering` or in
                              any other correction field, all of which
                              are computed exactly as before, and no
                              correction is applied, retrieved, or
                              selected again to produce it.
    learned_knowledge_context  Prompt 501: the directly relevant, already-
                              taught knowledge entry
                              (learned_knowledge_context.py's
                              `LearnedKnowledgeSelection.to_context()`
                              - status SELECTED, the stored `record`
                              and its `relationships`, exactly as the
                              existing KnowledgeSystem returned them),
                              when a caller explicitly supplies one -
                              copied straight through unchanged, the
                              SAME \"carry an already-built object
                              through, never compute it here\" posture
                              the correction fields above already use.
                              `build_generation_context()` does not look
                              anything up, does not decide relevance,
                              and this field does not influence
                              anything else built here. `None` unless a
                              caller supplies one - and Core only ever
                              supplies one when exactly one learned
                              knowledge entry is directly relevant - so
                              nothing changes for any existing caller.
                              Purely informational: it exposes what was
                              taught; it never becomes response text or
                              an invented answer.

`build_generation_context()` never invents a value for any of the
above - see response_planning.py's own module docstring for exactly
where each of these already comes from; this module reads them and
nothing else. Anything else a `ResponsePlan` carries (pattern
candidates, expression meanings, required items, understanding state,
warnings, response-action source, meaning name) is deliberately left
out of this bounded bridge.

No mutable-state leakage
-------------------------
`ResponsePlan.to_dict()` already returns a deep copy of everything it
holds (see response_planning.py); `build_generation_context()` reads
ONLY that (never `understanding` fields directly, never a live
`ResponsePlan` object's own attributes), and `ResponseGenerationContext`
stores its own deep copy of what it is given, then RETURNS a fresh deep
copy from `to_dict()`. So a caller that mutates a
`ResponseGenerationContext` it received - or the dict `to_dict()`
returned - can never reach back into the `ResponsePlan`, the
`LanguageUnderstandingResult` it was planned from, conversation state,
or any memory/knowledge object; and mutating the `ResponsePlan` /
understanding after the fact never changes a `ResponseGenerationContext`
already built from it.

Bounded
-------
Nothing here selects, ranks or trims anything itself: `context` is
exactly the bounded, already-relevance-selected conversation context
the existing pipeline attached to the `ResponsePlan` (see
response_planning.py / context/relevance.py); `references`,
`meaning_candidates` and `unresolved_requirements` are exactly the
plan's own already-bounded lists (response_planning.py's
MAX_EXPRESSION_MEANINGS / MAX_CONCEPT_REFERENCES). No conversation
history, memory database, or knowledge store is read or duplicated
here, and none is added.

Ambiguous / unresolved plans
------------------------------
An AMBIGUOUS or UNRESOLVED `ResponsePlan` produces a
`ResponseGenerationContext` with `status` set accordingly and
`response_action` left None (a `ResponsePlan` never computes one for
those statuses - see response_planning.py) - never silently turned
into a resolved response action, and never an arbitrarily chosen
`meaning`/`meaning_candidates` entry.

Integration
-----------
`ResponseGenerationRequest.generation_context`
(response_generation.py) exposes this for ANY backend, built from
whatever `response_plan` is already attached to the understanding -
existing callers that never look at it are completely unaffected.
`LocalLanguageModelBackend.generate_response()` (local_model_backend.py)
additionally passes it into `build_inference_request()`
(local_model_mapping.py), which forwards it, unmodified, as
`InferenceRequest.generation_context` (inference.py) - additional
structured input next to the existing prompt construction, never a
replacement for it, and never a change to model loading, readiness or
fallback selection. The deterministic fallback backend needs no
change: it still returns STATUS_DEFERRED and generates no text (see
response_generation.py's own module docstring for why), and the SAME
`ResponseGenerationRequest.generation_context` property already makes
this context available for it too, through the one existing interface.
"""

import copy

from .response_planning import ResponsePlan, STATUS_RESOLVED, STATUS_AMBIGUOUS, STATUS_UNRESOLVED
from .language_guidance import build_language_guidance
from .learned_response_pattern_selection import select_learned_response_pattern
from .learned_response_pattern_binding import bind_learned_response_pattern
from .learned_response_pattern_rendering import render_learned_response_pattern

# The only ResponsePlan fields this bridge reads (see module docstring).
_PLAN_FIELDS = (
    "original_message", "normalized_input", "status", "response_action", "meaning",
    "meaning_candidates", "matched_pattern", "variables", "active_topic", "references",
    "context", "detected_language", "locale", "unresolved_requirements",
    # Prompt 575: forwarded directly from the plan - see module docstring's
    # `correction_application_result_usable` entry.
    "correction_application_result_usable",
)


class ResponseGenerationContext:
    """Plain, JSON-shaped, read-only bridge object - see the module
    docstring. Same conventions as `LanguageContext`
    (language_context.py) and `ResponsePlan` (response_planning.py): a
    value holder with `to_dict()`, never anything that validates by
    raising."""

    def __init__(self, original_message, status, response_action, meaning, meaning_candidates,
                 matched_pattern, variables, active_topic, references, context, language, locale,
                 unresolved_requirements, language_guidance=None,
                 response_pattern_selection=None, response_pattern_binding=None,
                 response_pattern_rendering=None, correction_lookup_context=None,
                 correction_application_candidate=None, correction_application_result=None,
                 verified_correction_response_input=None, corrected_response_target=None,
                 learned_knowledge_context=None, correction_application_result_usable=False,
                 normalized_input=None):
        self.original_message = original_message
        # Prompt 610: additive, defaults to None for legacy direct
        # construction - see the module docstring's `normalized_input`
        # entry. Forwarded verbatim from `ResponsePlan.normalized_input`;
        # never derived, transformed, or re-normalized here, and never
        # modifies `original_message` above.
        self.normalized_input = normalized_input
        self.status = status
        self.response_action = response_action
        self.meaning = meaning
        self.meaning_candidates = meaning_candidates
        self.matched_pattern = matched_pattern
        self.variables = variables
        self.active_topic = active_topic
        self.references = references
        self.context = context
        self.language = language
        self.locale = locale
        self.unresolved_requirements = unresolved_requirements
        # Prompt 433: LearnedLanguageGuidance.to_dict(), or None - see
        # language_guidance.py. Additive; every field above is unchanged.
        self.language_guidance = language_guidance
        # Prompt 434: LearnedResponsePatternSelection.to_dict(), or None -
        # see learned_response_pattern_selection.py. Additive; every field
        # above is unchanged.
        self.response_pattern_selection = response_pattern_selection
        # Prompt 435: LearnedResponsePatternBinding.to_dict(), or None - see
        # learned_response_pattern_binding.py. Additive; every field above
        # is unchanged.
        self.response_pattern_binding = response_pattern_binding
        # Prompt 436: LearnedResponsePatternRendering.to_dict(), or None - see
        # learned_response_pattern_rendering.py. Additive; every field above
        # is unchanged.
        self.response_pattern_rendering = response_pattern_rendering
        # Prompt 467: the CorrectionLookupContext (Prompt 465/466) carried
        # through unchanged from the LanguageUnderstandingResult this
        # context was built from, or None. Informational only - never
        # read by, or influences, anything else built here. See module
        # docstring's `correction_lookup_context` entry above.
        self.correction_lookup_context = correction_lookup_context
        # Prompt 471: the CorrectionApplicationCandidate (Prompt 470),
        # when a caller explicitly supplies one, or None. Additive; every
        # field above is unchanged, and this field is never computed or
        # decided here - purely informational. See module docstring's
        # `correction_application_candidate` entry above.
        self.correction_application_candidate = correction_application_candidate
        # Prompt 483: the CorrectionApplicationResult (Prompt 474/478/479),
        # when a caller explicitly supplies one, or None. Additive; every
        # field above is unchanged, and this field is never computed,
        # applied, validated, or interpreted here - purely informational.
        # See module docstring's `correction_application_result` entry
        # above.
        self.correction_application_result = correction_application_result
        # Prompt 575: forwarded directly from `ResponsePlan.
        # correction_application_result_usable` (Prompt 574) - never
        # independently recomputed here. Additive; every field above is
        # unchanged, and this field plays no part in
        # `guidance`/`selection`/`binding`/`rendering` or any other
        # correction field. Defaults to False, the SAME safe default
        # `ResponsePlan` itself uses when it carries no result. See
        # module docstring's `correction_application_result_usable`
        # entry above.
        self.correction_application_result_usable = bool(correction_application_result_usable)
        # Prompt 487: the VerifiedCorrectionResponseInput (Prompt 485),
        # when a caller explicitly supplies one, or None. Additive; every
        # field above is unchanged, and this field is never computed,
        # applied, matched, or interpreted here - purely informational.
        # See module docstring's `verified_correction_response_input`
        # entry above.
        self.verified_correction_response_input = verified_correction_response_input
        # Prompt 494: the prepared corrected response target text (see
        # corrected_response_target.py's `prepare_corrected_response_target()`,
        # Prompt 493), when a caller explicitly supplies one, or None.
        # Additive; every field above is unchanged, and this field is
        # never computed, matched, or applied here - purely informational,
        # carried straight through exactly as given. Building this
        # `ResponseGenerationContext` never derives this value on its
        # own; see with_corrected_response_target()
        # (corrected_response_target_context.py) for the one place that
        # attaches it from an existing `ResponseGenerationRequest`.
        self.corrected_response_target = corrected_response_target
        # Prompt 501: the directly relevant learned knowledge entry
        # (LearnedKnowledgeSelection.to_context()), when a caller
        # explicitly supplies one, or None. Additive; every field above
        # is unchanged, and this field is never looked up, matched or
        # interpreted here - purely informational. See module
        # docstring's `learned_knowledge_context` entry above.
        self.learned_knowledge_context = learned_knowledge_context

    @property
    def resolved(self):
        return self.status == STATUS_RESOLVED

    @property
    def ambiguous(self):
        return self.status == STATUS_AMBIGUOUS

    @property
    def unresolved(self):
        return self.status == STATUS_UNRESOLVED

    def __repr__(self):
        return (f"ResponseGenerationContext(status={self.status!r}, "
                f"response_action={self.response_action!r})")

    def to_dict(self):
        """A fresh deep copy every call (see module docstring "No
        mutable-state leakage") - mutating the returned dict can never
        change this object's own state, and this object's own state
        can never be reached through it."""
        correction_lookup_context = (
            self.correction_lookup_context.to_dict()
            if hasattr(self.correction_lookup_context, "to_dict")
            else self.correction_lookup_context
        )
        correction_application_candidate = (
            self.correction_application_candidate.to_dict()
            if hasattr(self.correction_application_candidate, "to_dict")
            else self.correction_application_candidate
        )
        correction_application_result = (
            self.correction_application_result.to_dict()
            if hasattr(self.correction_application_result, "to_dict")
            else self.correction_application_result
        )
        verified_correction_response_input = (
            self.verified_correction_response_input.to_dict()
            if hasattr(self.verified_correction_response_input, "to_dict")
            else self.verified_correction_response_input
        )
        return copy.deepcopy({
            "original_message": self.original_message,
            # Prompt 610: forwarded verbatim - see the module docstring.
            "normalized_input": self.normalized_input,
            "status": self.status,
            "response_action": self.response_action,
            "meaning": self.meaning,
            "meaning_candidates": self.meaning_candidates,
            "matched_pattern": self.matched_pattern,
            "variables": self.variables,
            "active_topic": self.active_topic,
            "references": self.references,
            "context": self.context,
            "language": self.language,
            "locale": self.locale,
            "unresolved_requirements": self.unresolved_requirements,
            "language_guidance": self.language_guidance,
            "response_pattern_selection": self.response_pattern_selection,
            "response_pattern_binding": self.response_pattern_binding,
            "response_pattern_rendering": self.response_pattern_rendering,
            "correction_lookup_context": correction_lookup_context,
            "correction_application_candidate": correction_application_candidate,
            "correction_application_result": correction_application_result,
            "correction_application_result_usable": self.correction_application_result_usable,
            "verified_correction_response_input": verified_correction_response_input,
            "corrected_response_target": self.corrected_response_target,
            "learned_knowledge_context": (
                self.learned_knowledge_context.to_dict()
                if hasattr(self.learned_knowledge_context, "to_dict")
                else self.learned_knowledge_context
            ),
        })


def build_generation_context(response_plan, sentence_structure=None,
                              correction_lookup_context=None,
                              correction_application_candidate=None,
                              correction_application_result=None,
                              verified_correction_response_input=None,
                              learned_knowledge_context=None):
    """The `ResponseGenerationContext` for `response_plan` (a
    `ResponsePlan`, or its `to_dict()`). Reads only the fields listed
    in this module's docstring, each already a deep copy
    (`ResponsePlan.to_dict()` guarantees this - see
    response_planning.py); this function additionally deep-copies what
    it stores, so the returned object shares no mutable structure with
    `response_plan` even when a caller passes a live `ResponsePlan`
    whose own attributes it later mutates. A value that is neither
    raises TypeError - the same contract `ResponsePlanner.plan()`
    already follows for its own `understanding` argument.

    `sentence_structure` (Prompt 433, optional) - already-existing data,
    typically `understanding.learned_sentence_structure` (Prompt 422);
    never computed here. Forwarded, unchanged, into `language_guidance`
    (language_guidance.py) - the one piece of learned-language guidance
    a `ResponsePlan` alone cannot supply (see that module's own
    docstring for why). Omitted (the default), `language_guidance.
    sentence_structure` is simply None; nothing else about this
    function's behavior changes.

    `correction_lookup_context` (Prompt 467, optional) - already-existing
    data, typically `understanding.correction_lookup_context` (Prompt
    466's `CorrectionLookupContext`); never looked up or computed here.
    Carried straight through, unread and unmodified, onto the returned
    `ResponseGenerationContext.correction_lookup_context` - it plays no
    part in `guidance`/`selection`/`binding`/`rendering` above, all of
    which are computed exactly as before, from `response_plan` and
    `sentence_structure` alone. Omitted (the default), the returned
    context's `correction_lookup_context` is simply None; nothing else
    about this function's behavior changes.

    `correction_application_candidate` (Prompt 471, optional) -
    already-existing data, typically `understanding.
    correction_application_candidate` (Prompt 470's
    `CorrectionApplicationCandidate`); never built, chosen, or applied
    here. Carried straight through, unread and unmodified, onto the
    returned `ResponseGenerationContext.correction_application_candidate`
    - it plays no part in `guidance`/`selection`/`binding`/`rendering`
    or in `correction_lookup_context` above, all of which are computed
    exactly as before. Omitted (the default), the returned context's
    `correction_application_candidate` is simply None; nothing else
    about this function's behavior changes.

    `correction_application_result` (Prompt 483, optional) -
    already-existing data, typically a `CorrectionApplicationResult`
    (Prompt 474/478/479) already produced and verified by Prompt 482's
    `apply_correction_request_with_validation()`; never applied,
    validated, re-verified, or interpreted here. Carried straight
    through, unread and unmodified, onto the returned
    `ResponseGenerationContext.correction_application_result` - it
    plays no part in `guidance`/`selection`/`binding`/`rendering` or in
    `correction_lookup_context`/`correction_application_candidate`
    above, all of which are computed exactly as before, and its own
    `status` (`APPLIED`/`NOT_APPLIED`/`FAILED`) is never branched on or
    converted here. Omitted (the default), the returned context's
    `correction_application_result` is simply None; nothing else about
    this function's behavior changes.

    `correction_application_result_usable` (Prompt 575) - not a
    parameter of this function; it is read directly off `response_plan`
    the SAME way every other plan field above (`status`,
    `response_action`, etc.) already is, since it is `ResponsePlan`'s
    OWN Prompt 574 field, not separately supplied data like the
    correction objects above. Forwarded onto the returned
    `ResponseGenerationContext.correction_application_result_usable`
    unchanged; `False` when `response_plan` carries no such field (the
    common case for a plan built before Prompt 574). Never
    independently recomputed, and never influences
    `guidance`/`selection`/`binding`/`rendering` or any other field
    built here.

    `verified_correction_response_input` (Prompt 487, optional) -
    already-existing data, typically a `VerifiedCorrectionResponseInput`
    (Prompt 485, verified_correction_response_input.py); never built,
    matched, or applied here. Carried straight through, unread and
    unmodified, onto the returned `ResponseGenerationContext.
    verified_correction_response_input` - it plays no part in
    `guidance`/`selection`/`binding`/`rendering` or in
    `correction_lookup_context`/`correction_application_candidate`/
    `correction_application_result` above, all of which are computed
    exactly as before, and it never changes the generated response
    text. Omitted (the default), the returned context's
    `verified_correction_response_input` is simply None; nothing else
    about this function's behavior changes.

    `learned_knowledge_context` (Prompt 501, optional) - already-existing
    data, typically `understanding.learned_knowledge_context` (the
    `to_context()` of a SELECTED `LearnedKnowledgeSelection`); never
    looked up, matched, ranked or interpreted here. Deep-copied and
    carried straight through onto the returned
    `ResponseGenerationContext.learned_knowledge_context` - it plays no
    part in `guidance`/`selection`/`binding`/`rendering` or in any
    correction field above, all of which are computed exactly as before.
    Omitted (the default), it is simply None; nothing else about this
    function's behavior changes."""
    if isinstance(response_plan, ResponsePlan):
        data = response_plan.to_dict()
    elif isinstance(response_plan, dict):
        data = copy.deepcopy(response_plan)
    else:
        raise TypeError("response_plan must be a ResponsePlan or its to_dict()")

    guidance = build_language_guidance(response_plan, sentence_structure=sentence_structure)
    # Prompt 434: selected from the SAME plan and the guidance just built.
    selection = select_learned_response_pattern(response_plan, guidance)
    # Prompt 435: the selected pattern's variables, bound from the SAME
    # plan, guidance and selection.
    binding = bind_learned_response_pattern(response_plan, selection, guidance)
    # Prompt 436: the bound pattern's template rendered from the binding just built.
    rendering = render_learned_response_pattern(binding)

    return ResponseGenerationContext(
        original_message=data.get("original_message"),
        # Prompt 610: forwarded directly from the SAME `response_plan.
        # to_dict()` this function already reads every other plan field
        # from - never recomputed, never re-normalized. Missing on a plan
        # built before Prompt 609 (or a bare dict lacking the key) safely
        # defaults to None.
        normalized_input=data.get("normalized_input"),
        status=data.get("status"),
        response_action=data.get("response_action"),
        meaning=data.get("meaning"),
        meaning_candidates=list(data.get("meaning_candidates") or []),
        matched_pattern=data.get("matched_pattern"),
        variables=dict(data.get("variables") or {}),
        active_topic=data.get("active_topic"),
        references=list(data.get("references") or []),
        context=data.get("context"),
        language=data.get("detected_language"),
        locale=data.get("locale"),
        unresolved_requirements=list(data.get("unresolved_requirements") or []),
        language_guidance=guidance.to_dict(),
        response_pattern_selection=selection.to_dict(),
        response_pattern_binding=binding.to_dict(),
        response_pattern_rendering=rendering.to_dict(),
        correction_lookup_context=correction_lookup_context,
        correction_application_candidate=correction_application_candidate,
        correction_application_result=correction_application_result,
        # Prompt 575: forwarded directly from the SAME `response_plan.
        # to_dict()` this function already reads every other plan field
        # from - never recomputed. Missing on a plan built before Prompt
        # 574 (or a bare dict lacking the key) safely defaults to False,
        # the SAME default `ResponsePlan` itself uses.
        correction_application_result_usable=bool(
            data.get("correction_application_result_usable")),
        verified_correction_response_input=verified_correction_response_input,
        learned_knowledge_context=copy.deepcopy(learned_knowledge_context),
    )


def generation_context_from_understanding(understanding):
    """`ResponseGenerationContext` for the `response_plan` already
    attached to `understanding` (`LanguageIntelligenceCore` does this
    for every understanding it returns - see
    language_intelligence_core.py), or None when there is no plan to
    read yet (an understanding a caller built directly, or one a
    planner failed on - see `ResponsePlanner.plan`'s own failure
    handling in language_intelligence_core.py's
    `_attach_response_plan`). Never plans anything itself; never
    raises for a missing plan - only `build_generation_context`'s own
    TypeError for a plan of the wrong type propagates.

    Prompt 433: also reads `understanding.learned_sentence_structure`
    (Prompt 422, when present) and forwards it into
    `build_generation_context`, so `language_guidance.sentence_structure`
    is populated here exactly the way
    `generation_request_from_understanding`
    (response_generation_request.py) already populates its own
    `sentence_structure` field - the same understanding-only supplement,
    read once.

    Prompt 467: also reads `understanding.correction_lookup_context`
    (Prompt 466, when present - Prompt 465's `CorrectionLookupContext`)
    and forwards it, unread and unmodified, into
    `build_generation_context` - carried onto the returned context's own
    `correction_lookup_context` purely for later use; it does not affect
    anything computed here. Absent on `understanding` (the common case,
    and true for any pre-Prompt-466 understanding), this is simply None
    and behavior is exactly as before.

    Prompt 471: also reads `understanding.correction_application_candidate`
    (Prompt 470, when present - `CorrectionApplicationCandidate`) and
    forwards it, unread and unmodified, into `build_generation_context`
    - carried onto the returned context's own
    `correction_application_candidate` purely for later use; it does
    not affect anything computed here. Absent on `understanding` (the
    common case - no existing code path sets this attribute), this is
    simply None and behavior is exactly as before.

    Prompt 483: also reads `understanding.correction_application_result`
    (Prompt 474/478/479, when present - a `CorrectionApplicationResult`,
    typically one already produced and verified by Prompt 482's
    `apply_correction_request_with_validation()`) and forwards it,
    unread, unapplied, and unmodified, into `build_generation_context`
    - carried onto the returned context's own
    `correction_application_result` purely for later use; it does not
    affect anything computed here. Absent on `understanding` (the
    common case - no existing code path sets this attribute), this is
    simply None and behavior is exactly as before.

    Prompt 487: also reads `understanding.
    verified_correction_response_input` (Prompt 485, when present - a
    `VerifiedCorrectionResponseInput`) and forwards it, unread,
    unmatched, unapplied, and unmodified, into
    `build_generation_context` - carried onto the returned context's
    own `verified_correction_response_input` purely for later use; it
    does not affect anything computed here. Absent on `understanding`
    (the common case - no existing code path sets this attribute),
    this is simply None and behavior is exactly as before.

    Prompt 501: also reads `understanding.learned_knowledge_context`
    (when present - set by Core only when exactly one already-taught
    knowledge entry is directly relevant to the message; see
    learned_knowledge_context.py) and forwards it, unread and
    unmodified, into `build_generation_context`. Absent or None (the
    common case) behavior is exactly as before."""
    plan = getattr(understanding, "response_plan", None)
    if plan is None:
        return None
    sentence_structure = getattr(understanding, "learned_sentence_structure", None)
    correction_lookup_context = getattr(understanding, "correction_lookup_context", None)
    correction_application_candidate = getattr(
        understanding, "correction_application_candidate", None)
    correction_application_result = getattr(
        understanding, "correction_application_result", None)
    verified_correction_response_input = getattr(
        understanding, "verified_correction_response_input", None)
    learned_knowledge_context = getattr(understanding, "learned_knowledge_context", None)
    return build_generation_context(
        plan, sentence_structure=sentence_structure,
        correction_lookup_context=correction_lookup_context,
        correction_application_candidate=correction_application_candidate,
        correction_application_result=correction_application_result,
        verified_correction_response_input=verified_correction_response_input,
        learned_knowledge_context=learned_knowledge_context,
    )
